# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/plate_detection.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bproto/plate_detection.proto\"\x1d\n\x0cImageRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"W\n\x11\x44\x65tectionResponse\x12\x12\n\nplate_text\x18\x01 \x01(\t\x12\n\n\x02x1\x18\x02 \x01(\x05\x12\n\n\x02y1\x18\x03 \x01(\x05\x12\n\n\x02x2\x18\x04 \x01(\x05\x12\n\n\x02y2\x18\x05 \x01(\x05\x32\x42\n\x0ePlateDetection\x12\x30\n\x0b\x44\x65tectPlate\x12\r.ImageRequest\x1a\x12.DetectionResponseb\x06proto3')



_IMAGEREQUEST = DESCRIPTOR.message_types_by_name['ImageRequest']
_DETECTIONRESPONSE = DESCRIPTOR.message_types_by_name['DetectionResponse']
ImageRequest = _reflection.GeneratedProtocolMessageType('ImageRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMAGEREQUEST,
  '__module__' : 'proto.plate_detection_pb2'
  # @@protoc_insertion_point(class_scope:ImageRequest)
  })
_sym_db.RegisterMessage(ImageRequest)

DetectionResponse = _reflection.GeneratedProtocolMessageType('DetectionResponse', (_message.Message,), {
  'DESCRIPTOR' : _DETECTIONRESPONSE,
  '__module__' : 'proto.plate_detection_pb2'
  # @@protoc_insertion_point(class_scope:DetectionResponse)
  })
_sym_db.RegisterMessage(DetectionResponse)

_PLATEDETECTION = DESCRIPTOR.services_by_name['PlateDetection']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _IMAGEREQUEST._serialized_start=31
  _IMAGEREQUEST._serialized_end=60
  _DETECTIONRESPONSE._serialized_start=62
  _DETECTIONRESPONSE._serialized_end=149
  _PLATEDETECTION._serialized_start=151
  _PLATEDETECTION._serialized_end=217
# @@protoc_insertion_point(module_scope)
